In [1]:
! pip install pandas
! pip install matplotlib
import pandas as pd
import numpy as np
import pathlib
import matplotlib.pyplot as plt
! pip install scikit-learn


from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached matplotlib-3.9.2-cp311-cp311-win_amd64.whl (7.8 MB)
  Using cached contourpy-1.3.0-cp311-cp311-win_amd64.whl (217 kB)
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
  Using cached fonttools-4.54.1-cp311-cp311-win_amd64.whl (2.2 MB)
  Using cached kiwisolver-1.4.7-cp311-cp311-win_amd64.whl (56 kB)
  Using cached pillow-10.4.0-cp311-cp311-win_amd64.whl (2.6 MB)
     ------------------------------------ 106.9/106.9 kB 363.5 kB/s eta 0:00:00
  Using cached scikit_learn-1.5.2-cp311-cp311-win_amd64.whl (11.0 MB)
  Using cached scipy-1.14.1-cp311-cp311-win_amd64.whl (44.8 MB)
  Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)



[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


**Задание 1.
Выберите датасет, который имеет отношение к вашей области интересов или исследований. Датасет должен содержать неструктурированные данные, требующие разметки для решения конкретной задачи, например, анализа настроений или распознавания именованных сущностей.**

***В качестве примера я выбрал исследование, в котором анализируется возможность предсказать успешность IT проекта.
Сслыка: 
<https://www.kaggle.com/code/youhanlee/would-it-be-possible-to-predict-success-of-app/>***

In [2]:
#### Получение полного пути до файла с данными

filename = "AppleStore.csv"
print(filename)

#### Чтение файла Excel с данными
input_df = pd.read_csv(filename)
input_df.tail()

AppleStore.csv


Unnamed: 0          id                                 track_name  \
7192       11081  1187617475                                      Kubik   
7193       11082  1187682390                          VR Roller-Coaster   
7194       11087  1187779532      Bret Michaels Emojis + Lyric Keyboard   
7195       11089  1187838770  VR Roller Coaster World - Virtual Reality   
7196       11097  1188375727               Escape the Sweet Shop Series   

      size_bytes currency  price  rating_count_tot  rating_count_ver  \
7192   126644224      USD   0.00               142                75   
7193   120760320      USD   0.00                30                30   
7194   111322112      USD   1.99                15                 0   
7195    97235968      USD   0.00                85                32   
7196    90898432      USD   0.00                 3                 3   

      user_rating  user_rating_ver     ver cont_rating prime_genre  \
7192          4.5              4.5     1.3          4+       Games   
7193          4.5              4.5     0.9          4+       Games   
7194          4.5              0.0   1.0.2          9+   Utilities   
7195          4.5              4.5  1.0.15         12+       Games   
7196          5.0              5.0     1.0          4+       Games   

      sup_devices.num  ipadSc_urls.num  lang.num  vpp_lic  
7192               38                5         1        1  
7193               38                0         1        1  
7194               37                1         1        1  
7195               38                0         2        1  
7196               40                0         2        1

In [81]:
input_df.info()

data = df[['size_bytes','user_rating']]
data['user_rating_mark'] = ""
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7197 entries, 0 to 7196
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Unnamed: 0          7197 non-null   int64  
 1   id                  7197 non-null   int64  
 2   track_name          7197 non-null   object 
 3   size_bytes          7197 non-null   int64  
 4   currency            7197 non-null   object 
 5   price               7197 non-null   float64
 6   rating_count_tot    7197 non-null   int64  
 7   rating_count_ver    7197 non-null   int64  
 8   user_rating         7197 non-null   float64
 9   user_rating_ver     7197 non-null   float64
 10  ver                 7197 non-null   object 
 11  cont_rating         7197 non-null   object 
 12  prime_genre         7197 non-null   object 
 13  sup_devices.num     7197 non-null   int64  
 14  ipadSc_urls.num     7197 non-null   int64  
 15  lang.num            7197 non-null   int64  
 16  vpp_li

C:\Users\user\AppData\Local\Temp\ipykernel_8768\423642103.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['user_rating_mark'] = ""


size_bytes  user_rating user_rating_mark
0   100788224          4.0                 
1   158578688          4.0                 
2   100524032          3.5                 
3   128512000          4.0                 
4    92774400          4.5

In [82]:
data.to_csv('data_hw_9.csv', index=False)

In [110]:
# Читаем полученный файл
df = pd.read_csv('data_hw_9.csv')
df

size_bytes  user_rating  user_rating_mark
0      100788224          4.0               NaN
1      158578688          4.0               NaN
2      100524032          3.5               NaN
3      128512000          4.0               NaN
4       92774400          4.5               NaN
...          ...          ...               ...
7192   126644224          4.5               NaN
7193   120760320          4.5               NaN
7194   111322112          4.5               NaN
7195    97235968          4.5               NaN
7196    90898432          5.0               NaN

[7197 rows x 3 columns]

In [84]:
subset_auto, subset_manual = train_test_split(df, test_size=0.05, random_state=42)

# Сохраним второе подмножество
subset_manual.to_csv('subset_manual.csv', index=False)

# Деление множества поровну
#split_index = len(df) // 2

# Берем первую половину данных для автоматической разметки на основе правил
#subset_auto = df.iloc[:split_index, :]

# Берем вторую половину данных для ручной разметки в 4 задаче и сохраним его
#subset_manual = df.iloc[split_index:, :]
#subset_manual.to_csv('subset_manual.csv', index=False)

**Задание 2.
Выполните разметку на основе правил (rule-based labeling) на подмножестве выбранного датасета. Разработайте и реализуйте набор правил или условий, которые позволят автоматически присваивать метки данным на основе определенных шаблонов или критериев.**

In [85]:
# Определим под 1 подмножество правила
subset_auto

size_bytes  user_rating  user_rating_mark
6819   704336896          4.5               NaN
1374    21434368          4.5               NaN
4629   469181440          0.0               NaN
1964   226834432          4.5               NaN
91     133238784          3.5               NaN
...          ...          ...               ...
3772    43722752          2.5               NaN
5191    52270080          0.0               NaN
5226   192272384          4.5               NaN
5390  1030500352          3.5               NaN
860     85049344          4.5               NaN

[6837 rows x 3 columns]

In [89]:
### Функция для разметки основанной на правилах

### user_rating - оценка пользователей

def mark_user_rating(row):
    if row['user_rating'] >= 4.5:
        return 'high'
    elif 3.5 <= row['user_rating'] < 4.5:
        return 'medium'
    else:
        return 'low'

In [107]:
subset_auto['user_rating_mark'] = subset_auto.apply(mark_user_rating, axis=1)
subset_auto.head()

size_bytes  user_rating user_rating_mark
6819   704336896          4.5             high
1374    21434368          4.5             high
4629   469181440          0.0              low
1964   226834432          4.5             high
91     133238784          3.5           medium

In [91]:
subset_auto.value_counts()

size_bytes  user_rating  user_rating_mark
31624192    0.0          low                 3
51174400    0.0          low                 2
93580288    4.0          medium              2
35957760    4.5          high                2
40071168    4.5          high                2
                                            ..
3896109056  4.5          high                1
3956326400  0.0          low                 1
3968637952  0.0          low                 1
3975609344  0.0          low                 1
2998989824  3.5          medium              1
Name: count, Length: 6821, dtype: int64

In [92]:
subset_auto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6837 entries, 6819 to 860
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   size_bytes        6837 non-null   int64  
 1   user_rating       6837 non-null   float64
 2   user_rating_mark  6837 non-null   object 
dtypes: float64(1), int64(1), object(1)
memory usage: 213.7+ KB


In [111]:
subset_auto.to_csv('subset_auto.csv', index=False)

**Задача 3.
Выполните разметку вручную отдельного подмножества выбранного датасета с помощью выбранного вами инструмента разметки.**

In [105]:
# Проверим
df_man = pd.read_csv('subset_manual_check.csv')
df_man.head()

annotation_id  annotator                   created_at    id  lead_time  \
0            361          2  2024-10-14T20:49:40.208168Z  7198      3.427   
1            362          2  2024-10-14T20:49:51.741818Z  7199      1.540   
2            363          2  2024-10-14T20:50:05.698725Z  7200      4.021   
3            364          2  2024-10-14T20:50:13.974797Z  7201      1.799   
4            365          2  2024-10-14T20:50:19.979042Z  7202      1.449   

  sentiment  size_bytes                   updated_at  user_rating  \
0      high    79404032  2024-10-14T20:49:41.666588Z          5.0   
1      high    12734464  2024-10-14T20:49:51.741818Z          4.5   
2      high   308125696  2024-10-14T20:50:05.698725Z          4.0   
3       low    28471296  2024-10-14T20:50:13.974797Z          1.0   
4       low   404173824  2024-10-14T20:50:19.979042Z          3.0   

   user_rating_mark  
0               NaN  
1               NaN  
2               NaN  
3               NaN  
4               NaN

In [106]:
df_man.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   annotation_id     360 non-null    int64  
 1   annotator         360 non-null    int64  
 2   created_at        360 non-null    object 
 3   id                360 non-null    int64  
 4   lead_time         360 non-null    float64
 5   sentiment         360 non-null    object 
 6   size_bytes        360 non-null    int64  
 7   updated_at        360 non-null    object 
 8   user_rating       360 non-null    float64
 9   user_rating_mark  0 non-null      float64
dtypes: float64(3), int64(4), object(3)
memory usage: 28.3+ KB


**Задача 3.
Выполните разметку вручную отдельного подмножества выбранного датасета с помощью выбранного вами инструмента разметки.**

In [119]:
# Перенесем интересующие нас данные в столбцы в новый dataset для объединения
manual_to_merge_df = df_man[['size_bytes','user_rating','sentiment']]
old_column_name = 'sentiment'
new_column_name = 'user_rating_mark'
manual_to_merge_df.rename(columns={old_column_name: new_column_name}, inplace=True)

# сохраним новую версию файла
manual_to_merge_df.to_csv('subset_manual_check_1.csv', index=False)
manual_to_merge_df.head()



C:\Users\user\AppData\Local\Temp\ipykernel_8768\2234759337.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  manual_to_merge_df.rename(columns={old_column_name: new_column_name}, inplace=True)


size_bytes  user_rating user_rating_mark
0    79404032          5.0             high
1    12734464          4.5             high
2   308125696          4.0             high
3    28471296          1.0              low
4   404173824          3.0              low

In [116]:
# Объедините два подмножества в один набор данных
subset_auto_df = pd.read_csv('subset_auto.csv')
subset_auto_df.head()



size_bytes  user_rating user_rating_mark
0   704336896          4.5             high
1    21434368          4.5             high
2   469181440          0.0              low
3   226834432          4.5             high
4   133238784          3.5           medium

In [121]:
subset_manual_df = pd.read_csv('subset_manual_check_1.csv')
subset_manual_df.head()

size_bytes  user_rating user_rating_mark
0    79404032          5.0             high
1    12734464          4.5             high
2   308125696          4.0             high
3    28471296          1.0              low
4   404173824          3.0              low

In [122]:
merged_dataset = pd.concat([subset_auto_df, subset_manual_df], ignore_index=True)

# Сохраните объединенный набор данных в файл, замените 'merged_dataset.csv' на желаемое имя файла
merged_dataset.to_csv('merged_dataset.csv', index=False)

**Задача 5.
Обучите модель машинного обучения, используя объединенный набор размеченных данных.
Разделите датасет на обучающий и тестовый наборы и используйте обучающий набор для обучения модели.**

In [123]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression  # Пример модели

# чтение нашего объединенного файла
df_merge = pd.read_csv('merged_dataset.csv')
df_merge

size_bytes  user_rating user_rating_mark
0      704336896          4.5             high
1       21434368          4.5             high
2      469181440          0.0              low
3      226834432          4.5             high
4      133238784          3.5           medium
...          ...          ...              ...
7192    96872448          4.5             high
7193    21010210          4.0           medium
7194   408755200          2.5              low
7195    83575808          3.0              low
7196    30601216          3.5           medium

[7197 rows x 3 columns]

In [137]:
#Замена строк на числа в датасете
df_merge['user_rating_mark'] = df_merge['user_rating_mark'].replace({'low': 0, 'medium': 1, 'high': 2})

C:\Users\user\AppData\Local\Temp\ipykernel_8768\3894347623.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_merge['user_rating_mark'] = df_merge['user_rating_mark'].replace({'low': 0, 'medium': 1, 'high': 2})


In [138]:
df_merge['user_rating_mark'].unique()

array([2, 0, 1])

In [127]:
df_merge['user_rating'].unique()

array([4.5, 0. , 3.5, 5. , 2. , 3. , 4. , 2.5, 1.5, 1. ])

In [163]:
# Разделите данные на признаки (X) и целевую переменную (y)
X = df_merge.drop('size_bytes', axis = 1)  # Замените 'target_column_name' на имя вашей целевой переменной
y = df_merge['user_rating_mark']

# Разделим данные на обучающий и тестовый наборы
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  # Можно указать любой test_size и random_state


# Инициализируем модель машинного обучения (в данном случае пример с логистической регрессией)
model = LogisticRegression()  # Можно заменить на другую модель


# Обучим модель на обучающем наборе
model.fit(X_train, y_train)
# Оценим производительность модели на тестовом наборе
accuracy = model.score(X_test, y_test)
accuracy

1.0

**Задача 6.
Оценить эффективность обученной модели на тестовом датасете. Используйте подходящие метрики оценки. Интерпретируйте результаты и проанализируйте эффективность модели в решении задачи разметки**

***Для задачи классификации могут быть использованы метрики, такие как точность (accuracy), полнота (recall), точность (precision), F1-мера и кривая ROC-AUC. Для каждой метрики можно провести интерпретацию и анализ результатов.***.

In [164]:
# Предсказание меток классов на тестовом наборе
y_pred = model.predict(X_test)
y_pred

array([2, 1, 2, ..., 0, 2, 2])

In [165]:
# Оценка точности модели
accuracy_1 = accuracy_score(y_test, y_pred)
accuracy_1

1.0

In [159]:
# Classification Report для полного анализа метрик precision, recall и f1-score
classification_report(y_test, y_pred)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00       360\n           1       1.00      1.00      1.00       457\n           2       1.00      1.00      1.00       623\n\n    accuracy                           1.00      1440\n   macro avg       1.00      1.00      1.00      1440\nweighted avg       1.00      1.00      1.00      1440\n'

In [166]:
# Матрица ошибок (Confusion Matrix) для визуализации количества правильных и неправильных прогнозов
confusion_matrix(y_test, y_pred)

array([[360,   0,   0],
       [  0, 457,   0],
       [  0,   0, 623]])

***Вывод:
1. Мы выбрали довольно простой пример и по сути линейную регрессию, которая на 5% ручной разметки дала результат,
аналогичный разметке по правилу.
2. Модель обучилась идеально (accuracy = 1), можно использовать правило и модель для разметки.***